In [0]:
# http://pytorch.org/
from os import path
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())

accelerator = 'cu80' if path.exists('/opt/bin/nvidia-smi') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.3.0.post4-{platform}-linux_x86_64.whl torchvision
import torch

In [0]:
import torch.tensor

In [0]:
#Creating a torch tensor
x = torch.ones(4)
print(x)


 1
 1
 1
 1
[torch.FloatTensor of size 4]



In [0]:
#Converting to numpy
y = x.numpy()
print(y)

[1. 1. 1. 1.]


In [0]:
#making change to the tensor and checking the numpy array
x.add_(1)
print(x)
print(y)


 2
 2
 2
 2
[torch.FloatTensor of size 4]

[2. 2. 2. 2.]


We have added 1 to each of the initially defined tensor value and we could see that the changes has been well reflected in the numpy array. Now, we will see the exact opposite operation that is - converting numpy array to tensor and making changes to it. 

In [0]:
#Creating a numpy array
import numpy as np
a = np.ones(4)
print(a)

[1. 1. 1. 1.]


In [0]:
#Converting to tensor
b = torch.from_numpy(a)
print(b)


 1
 1
 1
 1
[torch.DoubleTensor of size 4]



In [0]:
#making changes to the numpy array and checking the tensor
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2.]

 2
 2
 2
 2
[torch.DoubleTensor of size 4]



So, we have added one to each of the values of the numpy array and the same has been reflected back. 